In [1]:
import pandas as pd
import numpy as np

In [8]:
d = pd.DataFrame([['AAA', 25, 25000],['BBB', 26, 26000],['CCC', 28, 280000]], columns=['Name', 'Age', 'Sal'], index=[101, 102,103])

In [9]:
d

Name  Age     Sal
101  AAA   25   25000
102  BBB   26   26000
103  CCC   28  280000

In [2]:
A = np.array([[2, 1, 1], [3, 2, 1], [2, 1, 2]])
A

array([[2, 1, 1],
       [3, 2, 1],
       [2, 1, 2]])

In [3]:
B = np.linalg.inv(A)
B

array([[ 3., -1., -1.],
       [-4.,  2.,  1.],
       [-1.,  0.,  1.]])

In [4]:
M=np.array([[1, 1],[-2,1]])
M

array([[ 1,  1],
       [-2,  1]])

In [5]:
M=np.linalg.inv(M)
M

array([[ 0.33333333, -0.33333333],
       [ 0.66666667,  0.33333333]])

In [6]:
M @ np.array([21,12])

array([ 3., 18.])

In [7]:
M @ np.array([25,28])

array([-1., 26.])

In [8]:
A = np.array([-3, 12])
A

array([-3, 12])

In [9]:
M @ A

array([-5.,  2.])

In [10]:
B1 = np.array([[1, 3, 4, 2], [3, 2 ,4 ,1], [1, 2, 3, 4], [3,2, 1,1]])

B2 = np.array([[1,1, 2,3], [3,3,2 ,1], [1,2,2,3], [1, 2, 2, 1]])

#B1 = B1.T

B1

array([[1, 3, 4, 2],
       [3, 2, 4, 1],
       [1, 2, 3, 4],
       [3, 2, 1, 1]])

In [11]:
B2

array([[1, 1, 2, 3],
       [3, 3, 2, 1],
       [1, 2, 2, 3],
       [1, 2, 2, 1]])

In [12]:
#  B1 = M @ B2

# M = INV(B2) .B1

In [13]:
B22 =np.linalg.inv(B2)
B22

array([[ 0.5 ,  0.5 , -0.5 , -0.5 ],
       [-1.  ,  0.  ,  1.  ,  0.  ],
       [ 0.75, -0.25, -1.  ,  1.  ],
       [-0.  , -0.  ,  0.5 , -0.5 ]])

In [14]:
R= B1@ B22
R = R.T
R.round(2)

array([[ 0.5 ,  2.5 ,  0.75,  0.25],
       [-0.5 ,  0.5 , -0.25,  1.25],
       [-0.5 , -3.  ,  0.5 ,  0.  ],
       [ 2.5 ,  2.  ,  0.5 , -1.  ]])

In [15]:
#Create B1
B1=np.array([[1,3,4,2], [3,2,4,1], [1,2,3,4], [3,2,1,1]])
#take its transpose so that columns are vectors of B1
B1=B1.T
B1

array([[1, 3, 1, 3],
       [3, 2, 2, 2],
       [4, 4, 3, 1],
       [2, 1, 4, 1]])

In [16]:
##### We notice that first column of the matrix B1 is the first vector of Basis B1 and so on

#similarly create B2
B2=np.array([[1,1,2,3],[3,3,2,1],[1,2,2,3],[1,2,2,1]])
#note that we didnt take transpose this time
B2

array([[1, 1, 2, 3],
       [3, 3, 2, 1],
       [1, 2, 2, 3],
       [1, 2, 2, 1]])

In [17]:
B2inB1=np.array([])
for b in B2: 
    #the reason we didnt take transpose this time is because we wanted to run it through a loop
    #Matrix M^-1 is obtained by writing basis vectors of B2 in B1 as columns of M
    #this for loop will calculate Basis vectors of B2 in B1
    
    
    #Here vectors of B2 are in standard basis (i,j,k,l) so to find its representation in B1, we simply take inverse 
    #of matrix B1 and multiply it by the vector.
    temp=(np.linalg.inv(B1) @ np.array(b).T)
    #append it in martix B2inB1
    B2inB1=np.append(B2inB1,temp, axis=0)

#take transpose of the matrix as stated above   
B2inB1=B2inB1.reshape(4,4).T

##### Thus our required M will just be inverse of B2inB1

M=np.linalg.inv(B2inB1).round(2)
M

array([[ 0.5 ,  2.5 ,  0.75,  0.25],
       [-0.5 ,  0.5 , -0.25,  1.25],
       [-0.5 , -3.  ,  0.5 ,  0.  ],
       [ 2.5 ,  2.  ,  0.5 , -1.  ]])

In [18]:
R.round(2)

array([[ 0.5 ,  2.5 ,  0.75,  0.25],
       [-0.5 ,  0.5 , -0.25,  1.25],
       [-0.5 , -3.  ,  0.5 ,  0.  ],
       [ 2.5 ,  2.  ,  0.5 , -1.  ]])

In [19]:
B1

array([[1, 3, 1, 3],
       [3, 2, 2, 2],
       [4, 4, 3, 1],
       [2, 1, 4, 1]])

In [20]:
V1= np.array([2, 4, 5,2])
#V1 = V1.T
V1

array([2, 4, 5, 2])

In [21]:
R @ V1

array([ 15.25,   2.25, -10.5 ,  13.5 ])

In [22]:
# Graded
B= np.array([[2 , -1],[-2, 5]])
B

array([[ 2, -1],
       [-2,  5]])

In [23]:
V = np.array([3, 2])
V

array([3, 2])

In [24]:
B.T @ V

array([2, 7])

In [27]:
## Graded

B = np.array([[3, 8], [1, -16]])
B

array([[  3,   8],
       [  1, -16]])

In [28]:
B = B.T
B

array([[  3,   1],
       [  8, -16]])

In [32]:
M = np.array([[3, 2]])
M = M.T

In [33]:
B @ M

array([[11],
       [-8]])

In [34]:
#v1 and v2 in terms of i and j
mat_V=np.array([2,3,1,-2]).reshape(2,2).T
#vectors of basis Bv in terms of v1 and v2
B_V1=np.array([2,-1])
B_V2=np.array([-2,5])
#converting Bv in terms of i and j from v1 and v2
M1=mat_V@B_V1
M2=mat_V@B_V2
#writing Bv as a matrix and taking its inverse
M=np.array([M1,M2]).T
M=np.linalg.inv(M)
print(M)

[[ 0.28571429  0.01785714]
 [ 0.14285714 -0.05357143]]


In [41]:
M1 = np.array([[3, 2]])
M1 

array([[3, 2]])

In [42]:
M1 = M1 @ M

In [43]:
M1

array([[ 1.14285714, -0.05357143]])

In [46]:
# Covariance
M = np.array([[2, 1], [3, 2], [2, 1], [5, 1]])
M

array([[2, 1],
       [3, 2],
       [2, 1],
       [5, 1]])

In [48]:
B =['X', 'Y']
df = pd.DataFrame(M, columns=B)
df

X  Y
0  2  1
1  3  2
2  2  1
3  5  1

In [49]:
np.cov(df.T)

array([[2.  , 0.  ],
       [0.  , 0.25]])